language: haskell

env:
  - GHCVER=7.4.2
  - GHCVER=7.6.3
  - GHCVER=7.8.2

before_install:
  - sudo add-apt-repository -y ppa:hvr/ghc
  - sudo apt-get update
  - sudo apt-get install -y -qq cabal-install-1.18 ghc-$GHCVER
  - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/1.18/bin:$PATH

install:
  - bash setup.sh
  - cabal sandbox init
  - cabal install --only-dependencies

script:
  - cabal build